### ISSUE TITLE
[Fabric 1.14 | 1.9.0.0] Startup Crash

### ISSUE THREAD

**Issue by Diamondman121314** [TheRandomLabs/VanillaDeathChest#11]
VanillaDeathChest seems to crash with a few mods when they are put together, those being [Pehkui](https://minecraft.curseforge.com/projects/pehkui) and [StatsKeeper (Fabric)](https://minecraft.curseforge.com/projects/stats-keeper-fabric). I have a [crash log](https://gist.github.com/Diamondman121314/94d592f3bb6c05f5de28485e64dce066).

**Comment by TheRandomLabs** [comment]
Thanks for reporting this. It's because we're both trying to modify `updatePostDeath` in `LivingEntity`. I'll see what I can do.
