### ISSUE TITLE
[1.14-1.9.1.0] Mixin conflict with CC: Tweaked 1.82.4

### ISSUE THREAD

**Issue by Cynosphere** [TheRandomLabs/VanillaDeathChest#12]
[Crash Log](https://mystb.in/woxeguhuve.cpp)

I [already reported to CC:T](https://github.com/SquidDev-CC/CC-Tweaked/issues/192) and was told it was because VanillaDeathChest uses `@Overwrite`.

**Comment by TheRandomLabs** [comment]
I'll just stop using `@Overwrite`s.
