### ISSUE TITLE
1.14 Game breaking bug

### ISSUE THREAD

**Issue by skytokox** [TheRandomLabs/VanillaDeathChest#13]
![2019-04-27_14 01 17](https://user-images.githubusercontent.com/50047674/56849471-0617a580-68f5-11e9-8cad-f3c7a3095103.png)
![2019-04-27_14 01 39](https://user-images.githubusercontent.com/50047674/56849472-0617a580-68f5-11e9-83fd-7a4dd7ab590f.png)
![2019-04-27_14 01 44](https://user-images.githubusercontent.com/50047674/56849473-06b03c00-68f5-11e9-9981-3791e6fb6521.png)

**Comment by TheRandomLabs** [comment]
Oh no, I screwed up.
