### ISSUE TITLE
NPE when using Quark's Extract button.

### ISSUE THREAD

**Issue by Giggitybyte** [TheRandomLabs/VanillaDeathChest#18]
When attempting to retrieve all items from a death chest using the *Extract* button added to chests by Quark, the game crashes with an NPE. 

During some light testing of this problem, I've found that it happens only with double death chests. Once you load the world back up, the left chest of the double chest will be gone leaving a single empty chest behind. This leftover chest does not get removed automatically and must be manually broken.

Eyeballing the logs leads me to believe this is an issue with Vanilla Death Chest. If not, let me know and I'll make an issue on Quark's repo.

Forge Version 1.14.4 - 28.1.111
Vanilla Death Chest Version 1.10.3.0
[Crash Report](https://gist.github.com/Giggitybyte/3a76426a056e2f3f0b8bffa15e86e345)
[Debug Log](https://gist.github.com/Giggitybyte/3a6abdfdf9e0fcc4ee5dd8d013f6cb42)

**Comment by TheRandomLabs** [comment]
Can you see if [this](https://www.curseforge.com/minecraft/mc-mods/vanilladeathchest/files/2857041) resolves the issue?

**Comment by Giggitybyte** [comment]
That seems to have fixed it. Thank you for the quick response!
