### ISSUE TITLE
Sometimes VDC will remain a extern chest when player have much items.

### ISSUE THREAD

**Issue by Simba98** [TheRandomLabs/VanillaDeathChest#19]
## Bug Describe
If a player have too much items, so VDC will spawn two chests to store the items. However, on Sponge Server, if player get back their items, one chest will disappear (it's right), but another will remain.
    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-0b58730f
    Sponge: 1.12.2-7.1.7
    SpongeForge: 1.12.2-2838-7.1.7
    Minecraft Forge: 14.23.5.2847
    JVM: 1.8.0_232/64-bit (Private Build)
    OS: Linux (5.1.7-050107-generic/amd64)

I'm not sure the bug is due to Sponge or VDC itself. It would be better if you can fix it.

##Tips

You should get the second half of chest firstly, when you get all items in the second half. The chest windows will be closed and the second half chest disappear. Then the remain chest is a free chest and can be opened by any player.
[dc41616e-907b-3e16-92bd-b7ed84a980da.zip](https://github.com/TheRandomLabs/VanillaDeathChest/files/4052018/dc41616e-907b-3e16-92bd-b7ed84a980da.zip)

Here is a short video to describe how to trig this bug.

**Comment by TheRandomLabs** [comment]
Can you see if [this](https://www.curseforge.com/minecraft/mc-mods/vanilladeathchest/files/2859418) fixes the issue?

**Comment by Simba98** [comment]
Thanks for your super-speed reply and fix. 

That one fixed my problem and have a new bug (maybe it exist in previous version)

When a death chest has been spawned, the owner directly destroys one of them, it will drop a chest item which named as Death Chest.

Here is a short video for that.
[6f583c1f-fe6a-30d6-a01f-b9840935465e.zip](https://github.com/TheRandomLabs/VanillaDeathChest/files/4052661/6f583c1f-fe6a-30d6-a01f-b9840935465e.zip)

**Comment by TheRandomLabs** [comment]
This is fixed in 1.12.2-1.10.3.4. :)
