### ISSUE TITLE
Crash upon death at nonvanilla heights

### ISSUE THREAD

**Issue by BaccarWozat** [TheRandomLabs/VanillaDeathChest#2]
Outside the Y bounds of 0-255, with tall world mods such as [Cubic Chunks](https://github.com/OpenCubicChunks/CubicChunks), deaths while carrying items has crashed with no chest spawned. Without items there is no crash, but also no chest (probably intended behavior). Using Forge 2611.

Crash log: https://pastebin.com/04zmnF4F
latest.log (crash is at the end): https://pastebin.com/wpuCK3Ny
fml-client-latest.log: https://pastebin.com/M9AefY1J

**Comment by TheRandomLabs** [comment]
This is fixed in 1.12.2-1.1.0.0. I'll release it after I fix another bug I'm working on.
