### ISSUE TITLE
Crashes when server starts

### ISSUE THREAD

**Issue by Neubulae** [TheRandomLabs/VanillaDeathChest#22]
https://hasteb.in/zoceroki.sql

**Comment by TheRandomLabs** [comment]
Whoops, apparently I used a client-sided method.

**Comment by Neubulae** [comment]
> Whoops, apparently I used a client-sided method.

awww c'mon

**Comment by TheRandomLabs** [comment]
Hey, to be fair, there's absolutely no reason this method should be client-sided.

**Comment by Neubulae** [comment]
> Hey, to be fair, there's absolutely no reason this method should be client-sided.

Well then that's fair enough.

**Comment by TheRandomLabs** [comment]
This is fixed in the release I'm about to upload.

**Comment by Neubulae** [comment]
> This is fixed in the release I'm about to upload.

Cool, quicc and good, thanccs
