### ISSUE TITLE
Latest Beta Crashes on launch

### ISSUE THREAD

**Issue by lorilith** [TheRandomLabs/VanillaDeathChest#25]
Seems i can run lithium and VDC 1.10.3.5
sadly, i crash on start with 1.10.3.6 

https://paste.ee/p/33Juh

**Comment by TheRandomLabs** [comment]
Can you see if 1.10.3.7 works?

**Comment by Linguardium** [comment]
all seems good now :)

**Comment by lorilith** [comment]
yep, all good
