### ISSUE TITLE
Can you make it possible to use "double chests" but as shulker boxes?

### ISSUE THREAD

**Issue by Pangamma** [TheRandomLabs/VanillaDeathChest#26]
Can you make it possible to use "double chests" but as shulker boxes? Alternatively, if we could use custom inventory sizes and custom inventory material names. 

Reason: I'm trying to run RLCraft, and I have vanilla death chest installed for it. Everything works great with double chests until you get to the lost cities dimension. If a house is haunted, you are not allowed to open chests until you clear the haunting. This is an obvious problem for people when they die and their stuff is trapped in a death chest. 

So to get around this I would like to use two shulker boxes or something. Can you make a tweak to support this for the 1.12.2 version?

**Comment by TheRandomLabs** [comment]
Done in 1.11.0.0.
