### ISSUE TITLE
Chests Explode When First Item is Removed

### ISSUE THREAD

**Issue by ghost** [TheRandomLabs/VanillaDeathChest#28]
In the 1.15.2 Fabric version, when an item is removed from a single chest, the block breaks and all items burst out. This is problematic when the chest is above lava.

**Comment by TheRandomLabs** [comment]
I can't replicate this issue. Could I have some more details? In the meantime, you can disable `misc.deathChestsDisappearWhenEmptied` in the configuration (`/vdcreload` if you don't want to restart the server).

**Comment by ghost** [comment]
Thanks. I can message you my server details if that might help. I am using several other mods. Any advice on narrowing down the cause on my end?

**Comment by TheRandomLabs** [comment]
Server details would be appreciated. :)

**Comment by ghost** [comment]
I forgot how gigantic my mod list is, so I've narrowed it down to the ones that are more closely related to inventory. I can give more information if you want.
Mods:
* Easier Chests (Client-side mod,but installed on the server too)
* Roughly Enough Items (Installed server-side but probably doesn't need to be there)
* Shulkularity

**Comment by TheRandomLabs** [comment]
Sorry for the late response, but I still cannot reproduce this issue with the three mods installed.

**Comment by TheRandomLabs** [comment]
Let me know if this is still an issue in the latest version.
