### ISSUE TITLE
Specify types of items to keep

### ISSUE THREAD

**Issue by crimulus** [TheRandomLabs/VanillaDeathChest#29]
This has been working really well for me, but primarily I've been looking for a mod that only saves any shulker boxes I might have had on me on death.  The rest would drop as usual.  This could be either a.) hard coded as a boolean KeepOnlyShulkerBoxes or b.) a configurable list of item IDs or name regexes or whatever were suitable.

Either of those would be great, and glancing through the code it seems as simple as adding that config option and then checking for it in lines 158-170 of DeathChestPlacer.java.  I'm not very experienced in Java or MC mods, so it's possible it's not that easy, but it'd be nice to have that flexibility.

Am happy to submit a PR even, if that helps, but I'll be kind of shooting in the dark.

**Comment by TheRandomLabs** [comment]
Done in 1.11.0.0.
