### ISSUE TITLE
[Feature Request] deatch chest just appears when chest in inventory

### ISSUE THREAD

**Issue by TobiPeterG** [TheRandomLabs/VanillaDeathChest#30]
Hello there,

I'd like to have a mod that saves my inventory when I die and this mod seems to do what I need.
For added "difficulty" I'd like to see an option that a chest is only placed when a chest is actually in your inventory/a double chest is placed when two chest are in the inventory. Those should be harvestable afterwards ofc as well, being a solution to the "endless chest" problem.
I'm playing currently on 1.12.2 and would like to know what you think about it. :)

Have a nice day!

**Comment by TheRandomLabs** [comment]
Done in 1.11.0.0.
