### ISSUE TITLE
Unexpected change to Fabric on CurseForge

### ISSUE THREAD

**Issue by CharZinta** [TheRandomLabs/VanillaDeathChest#31]
Latest release is a fabric based mod, as posted on CurseForge. This may be a known change if so please advise if not please update with forge version of the mod.

VanillaDeathChest 1.15.2-1.10.3.9-Fabric
Apr 19, 2020

**Comment by TheRandomLabs** [comment]
I may have to make a separate project for the Fabric version to avoid this issue.

**Comment by TheRandomLabs** [comment]
This should be fixed ~very shortly~ tomorrow.
