### ISSUE TITLE
1.16.1/1.11.0.3/Fabric - Chests not spawning on server

### ISSUE THREAD

**Issue by IdrisQe** [TheRandomLabs/VanillaDeathChest#35]
I have the mod installed serverside, but when a client without the mod dies, no chest is spawned, and items fly everywhere like normal. Does the mod require that clients still have Fabric installed? (I ask because many serverside mods work just fine when Vanilla clients join) I can't think of anything that would be messing this up since the modset I'm testing on my server currently is quite minimal.

Edit: Just tested with a Fabric client- chests are still not spawning. Even tested with a chest in my inventory. Nope.

**Comment by TheRandomLabs** [comment]
Can I see your log and configuration? I can't reproduce this.

**Comment by TheRandomLabs** [comment]
Let me know if this is still a problem.
