### ISSUE TITLE
Fabric version crashing the game on startup

### ISSUE THREAD

**Issue by DarthMitsu** [TheRandomLabs/VanillaDeathChest#36]
The current fabric version (vanilladeathchest-1.16.1-1.11.0.3-fabric.jar) of the mod seems not to work. Crashes my game on startup. No idea if it'S on my side, can't read these logs fully, but when I start the game with VanillaDeathChest disabled it work.

Here's the link to the crash log: https://paste.ee/p/GAZrm

**Comment by TheRandomLabs** [comment]
This is caused by tom5454/Toms-Fabric-Lib#1.
