### ISSUE TITLE
crash after death [forge-1.16.1]

### ISSUE THREAD

**Issue by SDUBZ** [TheRandomLabs/VanillaDeathChest#38]
VDC: vanilladeathchest-1.16.2-1.11.0.5
forge;1.16.1-32.0.108

crash:
[crash-2020-08-23_14.26.31-server.txt](https://github.com/TheRandomLabs/VanillaDeathChest/files/5113513/crash-2020-08-23_14.26.31-server.txt)

logs:
[latest.log](https://github.com/TheRandomLabs/VanillaDeathChest/files/5113516/latest.log)

**Comment by TheRandomLabs** [comment]
The latest 1.16.1 version should work.

**Comment by SDUBZ** [comment]
105 is the only version i see
why is 1.16.1 profiles seeing 1.16.2??

**Comment by TheRandomLabs** [comment]
https://www.curseforge.com/minecraft/mc-mods/vanilladeathchest/files/3008178
