### ISSUE TITLE
Death chest not spawning on server - Forge 1.12.2

### ISSUE THREAD

**Issue by nazzyz** [TheRandomLabs/VanillaDeathChest#39]
My apologies bringing up this issue again as I see it has been posted a couple of times, but I don't see where there was any resolution.  Looking for clarity if this is just a mistake on my side, or if this is actually a bug.
Forge version:
[19:22:25] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Starting minecraft server version 1.12.2
[19:22:26] [Server thread/INFO] [FML]: MinecraftForge v14.23.5.2854 Initialized

Mod version:
vanilladeathchest-1.12.2-1.11.0.2.jar

config:
https://paste.spigot.pl/laqomazubeqe.coffeescript

I've tried loading the mod and config file on a new single player world, removing the mod and loading a new single player world, then quitting and adding the mod.  Both new world and already created worlds both work fine and produce a chest with the contents.

When I load the same scenario on a new server, no chest appears.

This was a death on solid ground.  Message in console says a chest was spawned but no chest actually spawns and the items in my inventory have disappeared.  Nothing on the ground except an xp bubble.
[20:00:11] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: *** was slain by Zombie
[20:00:11] [Server thread/INFO] [vanilladeathchest]: Death chest for *** spawned at [BlockPos{x=-152, y=60, z=438}]

This was a death under water.  Message in console says a chest was spawned but no chest actually spawns and the items in my inventory have disappeared.  Nothing on the ground except an xp bubble.
[20:33:38] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: *** drowned
[20:33:38] [Server thread/INFO] [vanilladeathchest]: Death chest for *** spawned at [BlockPos{x=-170, y=58, z=424}]

I tested the same deaths with adding the mod to the client, and without in the client.  Same results.

I can post any other information if needed.  Thanks for your assistance.

**Comment by TheRandomLabs** [comment]
Sorry for the late reply, but I'm not sure what's going on here. Can I have a server `debug.log`?

**Comment by nazzyz** [comment]
Thanks for taking a look at this.  I've attached some info for you.  I created a new server instance and logged in.   I picked up some items and then committed suicide. (man that sounds morbid!)
[LogFiles.zip](https://github.com/TheRandomLabs/VanillaDeathChest/files/5284655/LogFiles.zip)
The logs show the chest says created but looking at the screenshot, no chest appeared.  Unfortunately there isn't much info pertaining to what happened on the server during that time.
Scratching my head with this one, I'll be glad to provide any additional info if needed.

**Comment by TheRandomLabs** [comment]
This seems to be specific to CatServer.
**EDIT:** The chest is being placed, but the items are not being put in, and because the chest is empty, it is automatically removed.

**Comment by TheRandomLabs** [comment]
The fix turned out to be rather simple. This should be fixed now!

**Comment by nazzyz** [comment]
You're a genius!  Thanks so much for working on this.
![fixed](https://user-images.githubusercontent.com/59720501/94354380-6b227e00-0048-11eb-863c-95aa8f1a5997.jpg)

**Comment by TheRandomLabs** [comment]
You're welcome!
