### ISSUE TITLE
Game rule missing localization

### ISSUE THREAD

**Issue by ChloeDawn** [TheRandomLabs/VanillaDeathChest#40]
**Mod version:** [1.16.2-1.11.0.6-fabric](https://www.curseforge.com/minecraft/mc-mods/vanilladeathchest-fabric/files/3036556)

![Screenshot of game rules menu](https://i.imgur.com/qWiQQTi.png)

**Comment by TheRandomLabs** [comment]
Thanks for bringing this to my attention. 😄
