### ISSUE TITLE
2.0.0 - breaking chests placed by me makes them invisible but doesn't actually break them

### ISSUE THREAD

**Issue by inikishev** [TheRandomLabs/VanillaDeathChest#47]
https://gist.github.com/idkman2021/f2778a1daf1f4d6132de4f3a600f1703
When I break my chests that I placed, they are still there (I can't go through the place the chest was at), I don't get the chest item. 
1.11.0.7 works fine on 1.16.5 and 2.0.0 has this issue

**Comment by TheRandomLabs** [comment]
Whoops, I never thought to test breaking a *regular* chest. 😛
