### ISSUE TITLE
Client crashes when dying near Botania Manastorm Charge (1.16.4)

### ISSUE THREAD

**Issue by maradotwebp** [TheRandomLabs/VanillaDeathChest#48]
When a Botania Manastorm Charge is activated, it shoots a few explosions in random directions. On the final one, the client crashes. (Tested it on a server, the server itself was fine.)

**MC Version**: 1.16.4 Forge
**Mod Version**: 1.11.0.7
**Log**: https://paste.ee/p/9xxic

**Comment by TheRandomLabs** [comment]
Thanks for reporting! I'm about to fix this.
