### ISSUE TITLE
[Fabric] Crash when dying to any mob

### ISSUE THREAD

**Issue by ImAK9** [TheRandomLabs/VanillaDeathChest#49]
https://github.com/TeamAOF/All-of-Fabric-3/issues/288

VanillaDeathChest version: 2.0.3

**Comment by TheRandomLabs** [comment]
This is a mod interaction, but I'm not sure which mod it is.

**Comment by ImAK9** [comment]
Hm FYI, I tried with vanilladeathchest-1.16.3-1.11.0.7-fabric.jar and everything works fine really.

**Comment by TheRandomLabs** [comment]
Yep, it's Campanion conflicting with my inventory backups. I'm going to see if I can implement them differently.

**Comment by ImAK9** [comment]
Alright, thanks! Let me know if you fix it, I marked newest AOF3 build as alpha for now.

**Comment by TheRandomLabs** [comment]
I should have a fix out very shortly. 😄
I'm going to have to look into preventing future conflicts with this though.

**Comment by TheRandomLabs** [comment]
Fix is out!

**Comment by ImAK9** [comment]
> Fix is out!

Thanks a ton for the quick fix!

**Comment by TheRandomLabs** [comment]
You're welcome! 😄
