### ISSUE TITLE
If death chest cannot spawn in area it doesn't

### ISSUE THREAD

**Issue by futurelucas4502** [TheRandomLabs/VanillaDeathChest#57]
I was playing on a world and died by failing to place down some water and the hole i was in was 2x2 but had ladders on one of the sides and my death chest didn't spawn and i saw in another issue that u can use /vdc place <uuid> however vdc place isn't a command for me even with cheats enabled what's going on and is there anyway to get back my stuff?

**Comment by futurelucas4502** [comment]
UPDATE: So after enabling an X-Ray mod it would seem my death chest just: 
![image](https://user-images.githubusercontent.com/48055553/112690274-69a90580-8e73-11eb-94d2-c3bc87975a00.png)
Decided to spawn over there in some lava:
![image](https://user-images.githubusercontent.com/48055553/112690322-7c233f00-8e73-11eb-8d8d-d3434aa2f31a.png)
Which is certainly... interesting?

**Comment by TheRandomLabs** [comment]
/vdc place is only in the 2.0.0 rewrite. That was probably the closest viable place that the mod could find. 😛

**Comment by futurelucas4502** [comment]
Ah I see that's fair enough i just gotta remember to pay more attention to the death chest spawned coordinates then
