### ISSUE TITLE
Death chest does not spawn on servers

### ISSUE THREAD

**Issue by dmodoomsirius** [TheRandomLabs/VanillaDeathChest#6]
Vanilla death chests do not spawn on fabric servers.

**Comment by TheRandomLabs** [comment]
Thanks for reporting this; I haven't extensively tested on Fabric.

**Comment by TheRandomLabs** [comment]
It looks like two of my mixins aren't being loaded server-side, but I have no idea why.

**Comment by TheRandomLabs** [comment]
Never mind, I've figured it out. This will be fixed in the next version.
