### ISSUE TITLE
[Crash] Optifine and Rift 1.13.2

### ISSUE THREAD

**Issue by ScottoMotto** [TheRandomLabs/VanillaDeathChest#7]
Bare modpack with Optifine (tested both E4 and E5) crash on launch
https://paste.ee/p/5J53J

**Comment by TheRandomLabs** [comment]
I couldn't reproduce this issue with OptiFine 1.13 HD U E4, 1.13.2 HD U E5 or 1.13.2 HD U E6 pre2.
![vanilladeathchest and optifine 1 13 2](https://user-images.githubusercontent.com/16755704/50717690-43092380-10dd-11e9-8e3d-49d44d23175c.png)
I can't look at OptiFine's source code to figure out what's wrong, but have you tried disabling all resource packs and shaders?

**Comment by ScottoMotto** [comment]
I don't currently have any resource pack or shaders. Here  is my optionof.txt. Maybe some setting in there matters?
[optionsof.txt](https://github.com/TheRandomLabs/VanillaDeathChest/files/2729121/optionsof.txt)

**Comment by ScottoMotto** [comment]
I figured out what it was. I had a WIP sky resource pack: https://github.com/ScottoMotto/ScottoMotto-Sky-Universal

I was trying out different colormaps and trying hide them by changing the extension to .bak... Mac sometimes fools you and doesn't actually change the extension. So it was .bak.png. 

For some reason every Rift mod but yours didn't mind this and the sky worked fine. Interesting... but thanks for helping to figure this out and sorry to waste your time chasing shadows.

You can close this issue.
