### ISSUE TITLE
[Issue] Wrongly placed chest cause crash

### ISSUE THREAD

**Issue by SupremeMarshal** [TheRandomLabs/VanillaDeathChest#8]
If a chest is being placed in the wrong place where it can't hold a double chest (this might also happen for a single chest) , then the server crash. The player fell from a high place below Y = 0. I'm using Cubic Chunk.

**Comment by SupremeMarshal** [comment]
I successfully reproduced the crash. I died in a 1x1 hole that was deep enough so the chest can't locate for a spot to be placed at.

**Comment by TheRandomLabs** [comment]
I couldn't reproduce this crash. See if 1.5.1.6 works, and if it doesn't, could you send me a crash report?

**Comment by SupremeMarshal** [comment]
have you tried to die by falling? And was the 1x1 hole deep enough? Also you needed to have your inventory full, or I think it just need to create a double chest.

**Comment by TheRandomLabs** [comment]
Yes. Before 1.5.1.6, it just created a double chest without crashing, and now it just creates a single chest when it detects that a double chest cannot be placed.
