### ISSUE TITLE
Can't pick up items with 1.14 VanillaDeathChest installed

### ISSUE THREAD

**Issue by MoonlightSystem** [TheRandomLabs/VanillaDeathChest#9]
Every time I have VanillaDeathChest 1.14-1.5.1.7-Fabric installed, I can't pick up items that i throw with the drop key or harvested items like wood logs, stone, ores, etc

**Comment by TheRandomLabs** [comment]
Whoops, I got confused with the new mappings and set the item pickup delay to infinity instead of 10.
